const constants = {
	'HYDRATE': 'LOGIN_HYDRATE',
	'REGISTER': 'LOGIN_REGISTER',
	'SEND': 'LOGIN_SEND',
	'UPDATE_ACCEPTED': 'LOGIN_UPDATE_ACCEPTED',
	'UPDATE_CAPTCHA': 'LOGIN_UPDATE_CAPTCHA',
	'UPDATE_EMAIL': 'LOGIN_UPDATE_EMAIL',
	'UPDATE_NAME': 'LOGIN_UPDATE_NAME',
	'UPDATE_PASSWORD': 'LOGIN_UPDATE_PASSWORD',
	'UPDATE_SECONDARY_PASSWORD': 'LOGIN_UPDATE_SECONDARY_PASSWORD',
	'VERIFY': 'LOGIN_VERIFY',
	'LOGOUT': 'LOGIN_LOGOUT',
	'FIX_AUTOFILL': 'LOGIN_FIX_AUTOFILL'
};

export default constants;
