const constants = {
	'LOGIN_REGISTER': 'LOGIN_REGISTER',
	'LOGIN_SEND': 'LOGIN_SEND',
	'LOGIN_UPDATE_ACCEPTED': 'LOGIN_UPDATE_ACCEPTED',
	'LOGIN_UPDATE_CAPTCHA': 'LOGIN_UPDATE_CAPTCHA',
	'LOGIN_UPDATE_EMAIL': 'LOGIN_UPDATE_EMAIL',
	'LOGIN_UPDATE_NAME': 'LOGIN_UPDATE_NAME',
	'LOGIN_UPDATE_PASSWORD': 'LOGIN_UPDATE_PASSWORD',
	'LOGIN_UPDATE_SECONDARY_PASSWORD': 'LOGIN_UPDATE_SECONDARY_PASSWORD',
	'LOGIN_VERIFY': 'LOGIN_VERIFY',
	'LOGOUT': 'LOGOUT'
};

export default constants;
